Repository chilek/lms, pull requests merged in 2020-05, with the labels that each got.

#1677 fix: ticket categories link color was other than declared in ui
  templates/default/rt/rtqueueviewboxrow.html
Labels: STABLE, STABLE-1.11.23, STABLE-24

#1678 devel: add support for tax categories in genfake script
  modules/genfake.php
Labels: STABLE, STABLE-24

#1680 bugfix: fixed more regression introduced accidentally by previous commits …
  templates/default/document/documentreference.html
  templates/default/message/messageadd.html
  templates/default/node/nodeaddbox.html
Labels: STABLE

#1682 ux/ui, sort persistent filters in UI alphabetically-ascending
  lib/SmartyPlugins/function.persistent_filter.php
Labels: STABLE, STABLE-24
