Repository chilek/lms, pull requests merged in 2021-12, with the labels that each got.

#2187 improvement: added unique key for dbinfo table
  doc/lms.mysql
  doc/lms.pgsql
  lib/LMSDB_common.class.php
  lib/upgradedb/mysql.2021120100.php
  lib/upgradedb/postgres.2021120100.php
Labels: STABLE, STABLE-25, STABLE-26

#2191 improvement: implemented {customerlist} in invoices list instead…
  lib/LMSManagers/LMSFinanceManager.php
  modules/invoicelist.php
  templates/default/customer/customerbalancebox.html
  templates/default/invoice/invoicelist.html
Labels: MASTER-ONLY

#2196 bugfix: get rid of travis error
  lib/Utils.php
Labels: STABLE

#2195 devel/improvement: add support for PLUGIN_SOFTWARE_VERSION and rename…
  lib/LMSPluginManager/LMSPlugin.php
  lib/LMSPluginManager/LMSPluginManager.php
  plugins/PluginExample/PluginExample.php
  templates/default/welcome/welcome_sysinfo_about_lms.html
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2197 devel/improvement: add support for displaying plugin software version…
  templates/default/welcome/welcome_sysinfo_about_lms.html
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2198 improvement: beautify displaying of plugins data in system informatio…
  js/locale/pl_PL.js
  lib/locale/pl_PL/strings.php
  templates/default/welcome/welcome_sysinfo_about_lms.html
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2199 improvement: add PLUGIN_DOC_URL and PLUGIN_REPO_URL data to system in…
  lib/LMSPluginManager/LMSPluginManager.php
  lib/locale/pl_PL/strings.php
  plugins/PluginExample/PluginExample.php
  templates/default/welcome/welcome_sysinfo_about_lms.html
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2200 improvement: beautify copied plugins data from system information panel
  templates/default/welcome/welcome_sysinfo_about_lms.html
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2201 improvement: beautify copied plugins data from system information pan…
  templates/default/welcome/welcome_sysinfo_about_lms.html
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2202 improvement: beautify copied plugins data from system information pan…
  templates/default/welcome/welcome_sysinfo_about_lms.html
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26, for_squash
