Repository chilek/lms, pull requests merged in 2021-10, with the labels that each got.

#2156 bugfix: save net device macs in DB as upper case string (chilek/lms-p…
  modules/netdevmac.php
  templates/default/netdev/netdevmaclist.html
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2157 bugfix: update net device mac in DB to upper case string (chilek/lms-…
  doc/lms.mysql
  doc/lms.pgsql
  lib/LMSDB_common.class.php
  lib/upgradedb/mysql.2021100500.php
  lib/upgradedb/postgres.2021100500.php
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2164 little code improvements/bugfixes
  modules/customer.inc.php
  modules/customerassignmentedit.php
  modules/customerprint.php
  modules/documentgen.php
  modules/netusage.php
  modules/noteadd.php
  modules/noteedit.php
  modules/paymentadd.php
  modules/paymentedit.php
  modules/rtticketadd.php
  modules/ukeincome.php
Labels: MASTER-ONLY

#2165 devel/codecleanup: little more code cleanup
  bin/lms-notify.php
  lib/LMSManagers/LMSCustomerManager.php
  lib/LMSManagers/LMSDivisionManager.php
  lib/LMSManagers/LMSNetNodeManager.php
  lib/SYSLOG.class.php
  lib/Sysinfo.class.php
  lib/Utils.php
  lib/dns.php
  modules/chooseip.php
  modules/customerassignmentedit.php
  modules/dbrecover.php
  modules/documentgen.php
  modules/eventschedule.php
  modules/netadd.php
  modules/netdevedit.php
  modules/nodeadd.php
  modules/taxrateedit.php
Labels: MASTER-ONLY

#2160 bugfix: removed SQL error when creating invoices in some conditions
  lib/LMSManagers/LMSFinanceManager.php
Labels: STABLE, STABLE-26

#2166 bugfix: fix ignoring discount change in invoice correction
  templates/default/invoice/invoicenotemodify.html
Labels: STABLE

#2168 bugfix: change invoice correction calculations when many data in posi…
  modules/invoicenote.php
Labels: STABLE
