Repository chilek/lms, pull requests merged in 2021-01, with the labels that each got.

#1880 Some small commits for rt module
  css/less/icons.less
  lib/SmartyPlugins/LMSSmartyPlugins.php
  lib/locale/pl_PL/strings.php
  modules/rtticketview.php
  templates/default/rt/rtqueueinfo.html
  templates/default/rt/rtqueueviewboxrow.html
  templates/default/rt/rtticketinfobox.html
Labels: MASTER-ONLY

#1912 improvement: allow to control showing events in the schedule and time…
  js/lms-ui-multiselect.js
  templates/default/event/eventlistboxrow.html
  templates/default/event/eventlistfilter.html
  templates/default/event/eventschedulebox.html
  templates/default/event/eventschedulefilter.html
Labels: STABLE

#1913 devel: add 'lms-ui-crossed' css class which shows crossing text gently
  css/less/lms-variables.less
  css/style.css
  css/style.less
Labels: MASTER-ONLY

#1922 bugfix: reset previous errors before next document is created in docu…
  modules/documentgen.php
Labels: STABLE, STABLE-1.11.23, STABLE-24, STABLE-25

#1934 improvement: add possibility to export configuration when only global…
  lib/locale/pl_PL/strings.php
  templates/default/config/configlist.html
Labels: STABLE

#1942 devel: include customer contacts editing in the database transaction
  modules/customeredit.php
Labels: STABLE, STABLE-24, STABLE-25
