Repository chilek/lms, pull requests merged in 2021-09, with the labels that each got.

#2128 devel: add 'class' attribute to custom link in net devices list
  templates/default/netdev/netdevlist.html
Labels: STABLE, STABLE-25, STABLE-26

#2131 devel: add common js function dedicated to financial calculations on …
  js/common.js
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2132 improvement: add rounding half away from zero method for negative val…
  js/customerassignmenthelper.js
  templates/default/invoice/invoicecontents.html
  templates/default/invoice/invoicenotemodify.html
  templates/default/tariff/tariffadd.html
  templates/default/tariff/tariffedit.html
Labels: STABLE

#2133 improvement: simplify rounding half away from zero js method for nega…
  js/common.js
Labels: STABLE, STABLE-25, STABLE-26

#2135 improvement: add support for rounding half away from zero js method f…
  js/common.js
Labels: STABLE, STABLE-25, STABLE-26

#2138 improvement: force entering numeric values for financial values in UI
  js/customerassignmenthelper.js
  templates/default/invoice/invoicecontents.html
  templates/default/invoice/invoicenotemodify.html
  templates/default/tariff/tariffadd.html
  templates/default/tariff/tariffedit.html
Labels: STABLE

#2126 devel/codecleanup: code simplification - use lms method instead of SQ…
  lib/LMSManagers/LMSHelpdeskManager.php
Labels: MASTER-ONLY

#2152 bugfix: more accurate priority checking
  lib/LMSManagers/LMSHelpdeskManager.php
  modules/rtmessageadd.php
  modules/rtnoteadd.php
Labels: STABLE

#2151 bugfix: correction of sql syntax
  lib/LMSManagers/LMSHelpdeskManager.php
Labels: MASTER-ONLY
