Repository chilek/lms, pull requests merged in 2021-05, with the labels that each got.

#2007 devel: add execute hooks for net device macs management
  modules/netdevmac.php
Labels: STABLE, STABLE-24, STABLE-25

#2015 enhancement: allow to save config list filter state as copy link
  lib/LMSManagers/LMSConfigManager.php
  modules/configedit.php
  modules/configlist.php
  templates/default/config/configedit.html
  templates/default/config/configlist.html
Labels: STABLE

#2021 codecleanup/devel: remove css class "lms-ui-icon-content" and convert few <A> to buttons
  css/less/icons.less
  templates/default/event/eventinfo.html
  templates/default/event/eventinfoshort.html
  templates/default/event/eventlistbox.html
  templates/default/event/eventlistbox_overdue.html
  templates/default/event/eventlistboxrow.html
  templates/default/event/eventlistheader.html
  templates/default/event/eventmodify.html
  templates/default/event/eventnote.html
  templates/default/event/eventschedulebox.html
  templates/default/event/eventsearch.html
  templates/default/netdev/netdevtickets.html
  templates/default/netnode/netnodedevices.html
  templates/default/netnode/netnodetickets.html
  templates/default/rt/rtheader.html
  templates/default/rt/rtqueueinfo.html
  templates/default/rt/rtqueuelist.html
  templates/default/rt/rtqueueviewboxrow.html
  templates/default/rt/rtticketchildren.html
  templates/default/rt/rtticketeventlist.html
  templates/default/rt/rtticketinfobox.html
  templates/default/rt/rtticketmessagesbox.html
  templates/default/rt/rtticketmodify.html
  templates/default/rt/rtticketparentinfo.html
  templates/default/rt/rtticketrelatedlist.html
  templates/default/rt/rtticketview.html
Labels: MASTER-ONLY

#2034 bugfix: change liability validation and set default liability quantit…
  lib/LMSManagers/LMSFinanceManager.php
Labels: STABLE, STABLE-24, STABLE-25
