Repository chilek/lms, pull requests merged in 2021-07, with the labels that each got.

#2062 bugfix: repair displaying mixed discount types in invoice and invoice…
  lib/LMSDocuments/LMSTcpdfInvoice.php
Labels: STABLE, STABLE-24, STABLE-25

#2063 improvement: removed unneded colons from rt/vlan module
  lib/locale/pl_PL/strings.php
  templates/default/rt/rtfilter.html
  templates/default/rt/rtheader.html
  templates/default/rt/rtmessageadd.html
  templates/default/rt/rtnoteadd.html
  templates/default/rt/rtprintindex.html
  templates/default/rt/rtqueuelist.html
  templates/default/rt/rtsearch.html
  templates/default/rt/rtticketchildren.html
  templates/default/rt/rtticketeventlist.html
  templates/default/rt/rtticketinfobox.html
  templates/default/rt/rtticketinfoshort.html
  templates/default/rt/rtticketmodify.html
  templates/default/rt/rtticketparentinfo.html
  templates/default/rt/rtticketprint.html
  templates/default/rt/rtticketrelatedlist.html
  templates/default/vlan/vlanmodify-dialog.html
Labels: MASTER-ONLY

#2060 improvements for customer tickets panel
  css/less/icons.less
  css/templates/customer/customertickets.less
  templates/default/customer/customertickets.html
Labels: MASTER-ONLY

#2070 bugfix: fix zeroing discount in invoice correction
  modules/invoicenote.php
Labels: STABLE, STABLE-25

#2071 bugfix: fix improperly displayed invoice discount column when discoun…
  lib/LMSDocuments/LMSTcpdfInvoice.php
Labels: STABLE, STABLE-25

#2072 bugfix: fix calculations during invoice correction repetitive edition
  modules/invoicenoteedit.php
Labels: STABLE, STABLE-25

#2073 bugfix: round each proforma balance before in lms-proforma-transform …
  bin/lms-proforma-transform.php
Labels: STABLE, STABLE-25

#2079 enhancement: support for calculations in net terms - fix discount cal…
  lib/LMSManagers/LMSFinanceManager.php
Labels: MASTER-ONLY

#2067 improvement: unification of category presentation and small translate bugfix
  css/style.less
  lib/locale/pl_PL/strings.php
  templates/default/rt/rtheader.html
  templates/default/rt/rtticketinfobox.html
Labels: MASTER-ONLY

#2084 bugfix: preserve tariff id when invoice position is edited
  templates/default/invoice/invoicecontents.html
Labels: STABLE, STABLE-24, STABLE-25

#2087 improvement: change invoice form display in new position
  lib/locale/pl_PL/strings.php
  templates/default/invoice/invoicecontents.html
Labels: STABLE, STABLE-24, STABLE-25

#2089 devel: fix translation for net calculations
  lib/locale/pl_PL/strings.php
  templates/default/customer/customerassignmenthelper.html
  templates/default/tariff/tariffadd.html
  templates/default/tariff/tariffedit.html
  templates/default/tariff/tariffinfo.html
Labels: MASTER-ONLY
