Repository chilek/lms, pull requests merged in 2021-02, with the labels that each got.

#1949 enhancement: introduce support for customer email address properties …
  doc/ChangeLog
  doc/lms.mysql
  doc/lms.pgsql
  lib/LMS.class.php
  lib/LMSDB_common.class.php
  lib/LMSManagers/LMSCustomerManager.php
  lib/customercontacttypes.php
  lib/locale/pl_PL/strings.php
  lib/upgradedb/mysql.2021020301.php
  lib/upgradedb/postgres.2021020301.php
  modules/customeredit.php
  templates/default/customer/customercontacts.html
  templates/default/customer/customerinfobox.html
Labels: MASTER-ONLY

#1798 bugfix: proper visibility of requestor in queueview form
  lib/LMSManagers/LMSHelpdeskManager.php
  templates/default/rt/rtqueueviewboxrow.html
Labels: STABLE, STABLE-24, STABLE-25

#1954 devel: add invoicenew_save_lock_tables hook
  modules/invoicenew.php
Labels: STABLE, STABLE-24, STABLE-25

#1953 imorvement: add tips to customer email properties (LMS+ #1224)
  templates/default/customer/customercontacts.html
  templates/default/customer/customerinfobox.html
Labels: MASTER-ONLY

#1955 improvement: separate configuration import function to dedicated form…
  doc/ChangeLog
  js/locale/pl_PL.js
  lib/accesstable.php
  lib/locale/pl_PL/strings.php
  lib/menu.php
  modules/configexport.php
  modules/configimport.php
  templates/default/config/configimport.html
  templates/default/config/configlist.html
Labels: MASTER-ONLY

#1957 bugfix: fix improperly displayed currency when invoice note is created
  lib/SmartyPlugins/LMSSmartyPlugins.php
Labels: STABLE

#1956 improvement: add 'phpui.supported_currencies' setting that specifies …
  doc/ChangeLog
  lib/SmartyPlugins/LMSSmartyPlugins.php
Labels: STABLE

#1964 devel: changelog
  doc/ChangeLog
Labels: MASTER-ONLY

#1965 devel: add label to alow to set network device as primary
  templates/default/netdev/netdevmacs.html
Labels: STABLE, STABLE-24, STABLE-25

#1966 enhancement: add support for configuration export to sql file in form…
  doc/ChangeLog
  modules/configexport.php
  templates/default/config/configlist.html
Labels: STABLE

#1870 improvement: change many inputs to one category multiselect in raports
  lib/locale/pl_PL/strings.php
  modules/rtprint.php
  templates/default/rt/rtprintindex.html
Labels: MASTER-ONLY
