Repository chilek/lms, pull requests merged in 2021-04, with the labels that each got.

#1980 bugfix: repair navigation in configuration management form
  modules/configadd.php
  modules/configdel.php
  modules/configedit.php
  modules/configlist.php
  templates/default/config/configadd.html
  templates/default/config/configedit.html
Labels: STABLE

#1983 bugfix: repair of table column period show/hide setting in userpanel
  userpanel/modules/finances/style/bclean/templates/userassignments.html
Labels: STABLE, STABLE-25

#1984 devel: change buttons layout in configuration list footer
  templates/default/config/configlist.html
Labels: STABLE

#1985 improvement: add selected section name to exported configuration file…
  modules/configexport.php
Labels: STABLE

#1982 Malutkie poprawki, które wyszły jak stawiałem sesję testową w jednej z firm
  modules/customerassignmentadd.php
  templates/default/customer/customerassignmenthelper.html
Labels: MASTER-ONLY

#1986 improvement: allow to hide 'don't scale images' option through Smarty…
  lib/SmartyPlugins/LMSSmartyPlugins.php
  templates/default/config/configimport.html
Labels: STABLE

#1988 bugfix: lost fa icon on notices
  userpanel/modules/notices/configuration.php
Labels: STABLE

#1990 improvement: add selected section name to exported sql configuration …
  modules/configexport.php
Labels: STABLE

#1991 enhancement: add possibility to import sql config file via UI
  lib/LMSManagers/LMSConfigManager.php
  lib/locale/pl_PL/strings.php
  modules/configimport.php
Labels: STABLE

#1989 enhancement: allow to control visibility of columns in userpanel finances module
  doc/ChangeLog
  doc/lms.mysql
  doc/lms.pgsql
  lib/LMSDB_common.class.php
  lib/upgradedb/mysql.2021040400.php
  lib/upgradedb/postgres.2021040400.php
  userpanel/modules/finances/functions.php
  userpanel/modules/finances/locale/pl_PL/strings.php
  userpanel/modules/finances/style/bclean/templates/userassignments.html
  userpanel/modules/finances/templates/setup.html
Labels: STABLE

#1994 codecleanup: optimization, use foreach in customertypes - invoiceprin…
  lib/locale/pl_PL/strings.php
  templates/default/print/printindex.html
Labels: MASTER-ONLY

#1995 bugfix: restore current liabilities values sum displaying
  templates/default/customer/customerassignments.html
Labels: STABLE, STABLE-25

#1993 enhancement: allow to set ticket priority as unknown/unset whitch is …
  doc/lms.mysql
  doc/lms.pgsql
  lib/LMSDB_common.class.php
  lib/LMSManagers/LMSHelpdeskManager.php
  lib/upgradedb/mysql.2021040900.php
  lib/upgradedb/postgres.2021040900.php
  modules/rtticketadd.php
  modules/rtticketedit.php
  templates/default/rt/rtfilter.html
  templates/default/rt/rtticketinfobox.html
  templates/default/rt/rtticketmodify.html
Labels: MASTER-ONLY

#1999 bugfix: missed forms when creating undefined priority
  templates/default/rt/rtmessageadd.html
  templates/default/rt/rtnoteadd.html
Labels: MASTER-ONLY

#2004 improvement: allow to set invoice pay type as bank loan
  lib/definitions.php
  lib/locale/pl_PL/strings.php
Labels: STABLE, STABLE-25
