Repository chilek/lms, pull requests merged in 2021-08, with the labels that each got.

#2091 bugfix: remove typo which influence on displaying number plans in inv…
  templates/default/invoice/invoiceedit.html
Labels: STABLE, STABLE-24, STABLE-25

#2023 improvement: changed modal to JS filled when modify
  templates/default/vlan/vlanlist.html
  templates/default/vlan/vlanmodify-dialog.html
Labels: MASTER-ONLY

#2097 bugfix: align label to icon in dropdown-buttons
  css/less/button.less
Labels: MASTER-ONLY

#2100 improvement: unification of font sizes in cnote and invoices table
  lib/LMSDocuments/LMSTcpdfInvoice.php
Labels: MASTER-ONLY

#2102 improvement: veritcaly-align icons to label in {button type=link} and…
  css/less/icons.less
Labels: STABLE, STABLE-25

#2101 improvement: hide resolved tickets in customer tickets panel (variable: phpui.default_show_closed_tickets, default: false)
  doc/ChangeLog
  lib/locale/pl_PL/strings.php
  modules/customer.inc.php
  templates/default/customer/customertickets.html
Labels: MASTER-ONLY

#2119 enhancement: ticket watching support
  css/less/icons.less
  doc/ChangeLog
  doc/lms.mysql
  doc/lms.pgsql
  lib/LMS.class.php
  lib/LMSDB_common.class.php
  lib/LMSManagers/LMSHelpdeskManager.php
  lib/LMSManagers/LMSHelpdeskManagerInterface.php
  lib/locale/pl_PL/strings.php
  lib/upgradedb/mysql.2021082800.php
  lib/upgradedb/postgres.2021082800.php
  modules/indicators.php
  modules/rtqueueview.php
  templates/default/indicators.html
  templates/default/rt/rtfilter.html
  templates/default/rt/rtticketinfobox.html
Labels: MASTER-ONLY
