Repository chilek/lms, pull requests merged in 2022-07, with the labels that each got.

#2267 bugfix: not optional tarrifs - was marked as optional
  templates/default/customer/customerassignmenthelper.html
Labels: STABLE, STABLE-25, STABLE-26

#2295 improvement: better placement of karma counter - moved away from cust…
  templates/default/customer/customerinfobox.html
Labels: MASTER-ONLY

#2284 improvement: callcenter plugin - allow to manipulate new ticket subje…
  contrib/tele.centrum.v2/index.php
Labels: MASTER-ONLY

#2230 devel: php7.2 is required from some time for lms-plus
  .travis.yml
  composer.json
Labels: MASTER-ONLY

#2263 improvement: allow to add icon for {customerselection} and {divisions…
  lib/SmartyPlugins/LMSSmartyPlugins.php
Labels: MASTER-ONLY

#2302 bugfix: fix PHP warnings
  lib/LMSManagers/LMSFinanceManager.php
Labels: STABLE-26

#2276 improvement: implemented {tax_rate_selection} for code unification
  lib/SmartyPlugins/LMSSmartyPlugins.php
  lib/SmartyPlugins/function.tax_rate_selection.php
  lib/locale/pl_PL/strings.php
Labels: MASTER-ONLY, for_squash
