Repository chilek/lms, pull requests merged in 2022-03, with the labels that each got.

#2234 bugfix: fix wrong balance calculation when tax is changed in invoice …
  modules/invoicenote.php
Labels: STABLE

#2237 bugfix: fix table locking for MySQL for CopyAddress method in locatio…
  lib/LMSManagers/LMSFinanceManager.php
  modules/invoicenew.php
  modules/invoicenote.php
  modules/noteadd.php
  modules/noteedit.php
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2244 improvement: allow to set pagelimit for vlanlist form (phpui.vlanlist…
  modules/vlanlist.php
  templates/default/vlan/vlanlist.html
Labels: STABLE, STABLE-26

#2245 improvement: show model hardware type in netdeviceinfo
  lib/LMSManagers/LMSNetDevManager.php
  lib/locale/pl_PL/strings.php
  templates/default/netdev/netdevinfobox.html
Labels: MASTER-ONLY

#2246 bugfix: align netdevtickets pane header
  templates/default/netdev/netdevtickets.html
Labels: MASTER-ONLY

#2248 enhancement: multi-entry history support in configuration mamagement
  modules/configadd.php
  modules/configdel.php
  modules/configedit.php
  modules/configlist.php
  templates/default/config/configadd.html
  templates/default/config/configdivisions.html
  templates/default/config/configdivisionusers.html
  templates/default/config/configedit.html
  templates/default/config/configlist.html
  templates/default/config/configusers.html
Labels: MASTER-ONLY, for_merge

#2249 improvements for document scan
  modules/documentscanadd.php
  templates/default/document/documentscanadd.html
Labels: MASTER-ONLY, for_merge
