Repository chilek/lms, pull requests merged in 2022-01, with the labels that each got.

#2208 bugfix: remove unnecessary characters from the invoice data (chilek/l…
  templates/default/invoice/invoicecontents.html
  templates/default/invoice/invoiceedit.html
  templates/default/invoice/invoicenew.html
  templates/default/invoice/invoicenotemodify.html
Labels: STABLE

#2209 bugfix: restore default system number plan when document save returns…
  js/lms-ui-numberplan-select.js
  lib/SmartyPlugins/LMSSmartyPlugins.php
  modules/numberplanhelper.php
Labels: STABLE

#2210 improvement: deny invoice note saving when invoice positions were not…
  modules/invoicenote.php
  modules/invoicenoteedit.php
  templates/default/invoice/invoicenotemodify.html
Labels: MASTER-ONLY

#2213 improvement: {fileupload} add accept parameter (eg. value ".pdf" mean…
  lib/SmartyPlugins/LMSSmartyPlugins.php
Labels: MASTER-ONLY

#2215 improvement: allow to view full sized/canavas image when uploading fi…
  js/lms-ui-fileupload.js
Labels: STABLE

#2220 enhancement: 'size' smarty modifier eases array size calculation and …
  lib/SmartyPlugins/LMSSmartyPlugins.php
Labels: STABLE, STABLE-24, STABLE-25, STABLE-26

#2223 bugfix: use numeric sorting instead of string sorting
  templates/default/vlan/vlanlist.html
  templates/default/vlan/vlanmodify-dialog.html
Labels: STABLE, STABLE-26

#2221 codecleanup: moved variables declaration to top, add fallback values…
  userpanel/modules/helpdesk/functions.php
  userpanel/modules/helpdesk/style/bclean/templates/helpdeskview.html
  userpanel/modules/helpdesk/templates/helpdeskreply.html
  userpanel/modules/helpdesk/templates/helpdeskview.html
Labels: MASTER-ONLY
